language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install --dev --prefer-source

after_script:
  - php vendor/bin/coveralls